version: '3'

services: 
    mysql: 
        image: mysql:5.7
        container_name: mysql
        command: '--innodb-use-native-aio=0 --character-set-server=utf8'
        restart: always
        tty: true
        ports: 
            - 3306:3306
        volumes: 
            - ./dbdata:/var/lib/mysql
            - ./mysql/scriptSQL:/docker-entrypoint-initdb.d
        environment: 
            - MYSQL_DATABASE=db-php
            - MYSQL_ROOT_PASSWORD=root 
            #- MYSQL_USER=root 
        networks: 
            - app-network

    app:
        container_name: app
        build: 
            context: ./php
        entrypoint: dockerize -wait tcp://mysql:3306 -timeout 60s php-fpm
        networks: 
            - app-network
            - nginx-network
        tty: true
        ports: 
            - 9000:9000
        depends_on: 
            - mysql

    nginx:
        container_name: nginx
        build:
            context: ./nginx
        networks: 
            - nginx-network
        ports:
            - 8000:80
        tty: true
        entrypoint: dockerize -wait tcp://app:9000 -timeout 60s /docker-entrypoint.sh
        command: ["nginx", "-g", "daemon off;"]
        depends_on: 
            - app
    
networks: 
    app-network: 
        driver: bridge
    nginx-network:
        driver: bridge